apiVersion: v1
kind: Service
metadata:
  name: chicago-service
spec:
  selector:
    app: chicago
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32030

---

apiVersion: v1
kind: Pod
metadata:
  name: chicago-app
  labels: 
    app: chicago
spec:
  containers:
    - name: chicago
      image: webwizardsusa/nyu-image
      ports:
        - containerPort: 80
          protocol: TCP
          name: chicagoport
  